(load "zig-out/lib/libbindings.so")
(define q (exec_query "((function_definition) @func)" '("/home/mike/test2.cpp")))
; (display (captures (match (car q))))
(display (matches_ExecQueryResult q))
(display "\n")
(display (ts_node_string (node (captures (car (matches_ExecQueryResult q))))))
(display "\n")
