[package]
name = "sizr-core"
version = "0.1.0"
authors = ["Michael Belousov <michael.belousov98@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"